# Generated by Django 3.0.4 on 2020-04-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('company_income', models.IntegerField()),
                ('company_security', models.IntegerField()),
                ('hacker_resources', models.IntegerField()),
                ('game_score', models.IntegerField()),
                ('best_game_score', models.IntegerField()),
            ],
        ),
    ]
